<?php
/**
 * @file
 * Attach JS and CSS assets on demand from javascript using l.js.
 */

/**
 * Implements hook_menu().
 */
function summoner_menu() {
  $items = array();
  $items['summoner/load/%'] = array(
    'page callback' => 'summoner_load_libraries',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_library().
 */
function summoner_library() {
  $libraries = array();
  $libraries['summoner'] = array(
    'title' => t('Summoner'),
    'website' => 'http://www.drupal.org/project/summoner',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'summoner') . '/assets/summoner.js' => array(),
    ),
    'dependencies' => array(
      array('system', 'drupal.ajax'),
    ),
  );
  return $libraries;
}

/**
 * Fetch library paths to load them with l.js.
 */
function summoner_load_libraries($id) {
  $libraries = explode(',', $_GET['libraries']);
  $attached['#attached'] = array('library' => array());
  foreach ($libraries as $library) {
    $attached['#attached']['library'][] = explode('/', $library);
  }
  $attached['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array('summoner-id' => $id),
  );
  $page = array(
    '#type' => 'ajax',
    '#commands' => array(ajax_command_invoke('body', 'summonerLoaded', array($id))),
  );
  drupal_render($attached);
  ajax_deliver($page);
}
